### PR TITLE
Add rename parameter to file download URLs

### LINKED ISSUE #862: Update FileUpload on front-end
Depends on #861 

## Motivation
At the moment, our files are uploaded to cloud storage using a GUID and without a file extension. This means that the filename the users originally had for their files are lost. This causes problems when downloading the file again especially for Windows users because Windows relies on file extensions to determine the file type, unlike Mac/Linux. The backend FileUpload API has been updated to accept a `rename` parameter and will set the filename to this before returning it to the client. If we keep track of the filename we want, the front-end can pass this to the File api when downloading a file. 

## Requirements
Update the [FileUpload](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/components/FileUpload.js) and [FormFileUpload](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/components/form/FormFileUpload.js) components such that when FileUpload calls props.onChange, it passes not just the GUID of the file that was uploaded, but a JSON object, converted to a string, that looks like this:
```
{
  "filename": "<UPLOADED_FILE_GUID>",
  "rename": "<ORIGINAL_FILE_NAME>"
}
```
The component should also be able to parse and load this JSON into its state if it's initialised with such a value.
Have a look at the FormMultiFile and MultiFileUpload components as an example of a component that uses complex state
Test this by ensuring that whenever a file is uploaded using the application form, that the Answer value is a string containing this JSON and not just the file GUID

Next, update the [AnswerValue component](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/components/answerValue/AnswerValue.js) so that the "file" type is compatible with the new JSON encoded file representation and also backwards compatible with the old GUID-only representation. 
- When the value is a string-encoded JSON object, the component displays the "rename" value instead of "Uploaded file" and the URL link is `{baseUrl + "/api/v1/file?filename=" + filename + "&rename=" + rename}` where `filename` and `rename` were extracted from the JSON. Remove the note about changing the filename in this case.
- When the value is just a single string (ie the string value doesn't start with "{" and end with "}"), then keep the existing behaviour.

### PR DESCRIPTION
**Pull request by gausam**
Closes #862

### CODE REVIEW

**Comment by gausam** [comment]
@avishkar58 Will these have to be updated as well?

- https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/components/answerValue/MultiFileValue.js#L10
- https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/pages/ResponsePage/ResponsePage.js#L161
- https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/pages/ResponsePage/ResponsePage.js#L168

**Comment by avishkar58** [comment]
> @avishkar58 Will these have to be updated as well?
> 
> * https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/components/answerValue/MultiFileValue.js#L10
> * https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/pages/ResponsePage/ResponsePage.js#L161
> * https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/pages/ResponsePage/ResponsePage.js#L168

Ah yes - good catch, those need to be updated too please! 
This PR looks great, so once you've updated those we can merge - thank you!

**Comment by gausam** [comment]
Will do!

**Comment by avishkar58** [comment]
Hi @gausam - please merge develop into your branches to fix the tests on CircleCI - thanks!

**Review by avishkar58 — APPROVED** [review]

**Comment by gausam** [comment]
Done!

**Pull request merged**
