### PR TITLE
Adding privacy policy to the webapp

### PR DESCRIPTION
**Pull request by nischalhp**
Resolving #72

### CODE REVIEW

**Comment by avishkar58** [comment]
Thanks @nischalhp - could you please add the PDF to the public directory and add a link to it in Baobab footer?

**Comment by nischalhp** [comment]
@avishkar58 I have moved the pdf to the public directory, but I have no idea how to add it in the footer appropriately. Should I just provide an ahref link in the app.js file in src?

@KaleabTessera

**Comment by KaleabTessera** [comment]
No stress, I added the link to the footer. @nischalhp

**Comment by nischalhp** [comment]
Whoohoo!!

**Pull request merged**
