### PR TITLE
Feature/review history

### PR DESCRIPTION
**Pull request by DonneStevenson**
Resolves issue #218

### CODE REVIEW

**Comment by DonneStevenson** [comment]
@jaderabbit  out of curiosity (I'm new to this) what would the alternative be?

**Comment by jaderabbit** [comment]
@DonneStevenson 
So for small ones, instead of this:
```
            reviews = reviews\
                .order_by(ReviewResponse.id)
```
This is significantly more readable:
`reviews = reviews.order_by(ReviewResponse.id)`

Annoyingly, python's multiline for long function chains is weird, but some recommended (and less horrifying) ways are here: https://stackoverflow.com/a/8818593/2282248

**Comment by avishkar58** [comment]
Good spot on the line endings - I was wondering why many of the diffs on previous PRs were nonsensical

**Comment by DonneStevenson** [comment]
@avishkar58  that's Amrits detective work on the line endings :)

**Comment by DonneStevenson** [comment]
@jaderabbit I have changed the queries to use brackets hope this is less horrifying now :D

**Comment by jaderabbit** [comment]
@DonneStevenson Much beauty. Such thanx

**Pull request merged**
