### PR TITLE
Fixes #107

### LINKED ISSUE #107: Data updates
Tracking issue for miscellaneous data updates required: 

- Update closing date for Indaba 2019 application form to 12 April 2019
- Update placeholder on "May we add your CV..." question to "Select an option..."  (it currently says Select **and** option...)
- Update "Academic" to "Academic Faculty" in user category

### PR DESCRIPTION
**Pull request by jaderabbit**
Fixed the data errors. 

Should we add `Flask-Admin` for very basic crud admin dashboard thing?
@avishkar58 @KaleabTessera Thoughts?

### CODE REVIEW

**Comment by avishkar58** [comment]
Migration failing on test for weird reasons again? :( 
Something like flask-admin sounds great! We'll need to do things like mark people as event reviewers etc fairly soon, so that's probably the best way instead of having to write admin forms/components etc from scratch

**Comment by KaleabTessera** [comment]
I agree Flask-Admin sounds like a great idea!

**Comment by jaderabbit** [comment]
@KaleabTessera I'm sure the database is created from scratch each time? Or does circleci actually cache the previous dockers? 

it looks like a new one to me. I'll spend time debugging later today

**Comment by KaleabTessera** [comment]
@jaderabbit Apologies, my mistake I thought the issue was happening at migrate-test step and the error message looks like a new issue (I misread it :( ) .

**Pull request merged**
