### PR TITLE
Stopped prev versions in test.

### PR DESCRIPTION
**Pull request by KaleabTessera**

### CODE REVIEW

**Comment by KaleabTessera** [comment]
Hmm that is weird that it does this only in Test :( 

So once merged, it doesn't deploy? Does it timeout when building the containers? Maybe we can just inc the timeout?

**Comment by jaderabbit** [comment]
@KaleabTessera It does it in prod as well. I actually have that problem right now :P

**Comment by jaderabbit** [comment]
@KaleabTessera Check out this: https://github.com/deep-learning-indaba/Baobab/pull/230

**Comment by jaderabbit** [comment]
Nevermind. It did eventually deploy. I must be going mad

**Comment by jaderabbit** [comment]
@KaleabTessera So it literally ignored the field which is as per the link in the PR above. :/ Annoying gcloud

**Pull request merged**
