### PR TITLE
fixed Issue #558

### PR DESCRIPTION
**Pull request by arunavkonwar**

### CODE REVIEW

**Comment by avishkar58** [comment]
Hey @arunavkonwar , there are a bunch of other tests that create application forms that are now failing. Please have a look. A pattern we've been using lately to address these somewhat brittle tests, is to add a helper method to utils/testing.py to create the entity in question. So you could add a `create_application_form(...)` method with some sensible defaults

**Comment by arunavkonwar** [comment]
@avishkar58 I suspect it might have something to do with the `nominations` flag being set to `nullable=False'. But I'll go with the procedure you mentioned. Thanks for the pointer.

**Comment by amritpurshotam** [comment]
Oh wait nevermind, you made another PR

**Comment by arunavkonwar** [comment]
@amritpurshotam this branch got messed up due to too many changes from all the developers at the same time, thus created a new one. I'm closing this. Thanks :)

**Pull request closed without merging**
