### PR TITLE
Feature/gcp circleci

### PR DESCRIPTION
**Pull request by KaleabTessera**
Things added:
- Circle ci -> gcp Continuous Integration for website.

@jaderabbit , We can add IP address of the API to webapp/env.test, then when we merge branches to develop, it will use the correct API urls.

### CODE REVIEW

**Comment by jaderabbit** [comment]
@KaleabTessera Let's add them as encrypted environment variables rather from circleci side.

**Comment by KaleabTessera** [comment]
@jaderabbit What would be the benefit of encrypting the API urls? Won't it still be visible from the network tab as API calls are made?

**Comment by jaderabbit** [comment]
@KaleabTessera Yes, that is true. Feels wrong being in the repo for some reason.

**Comment by jaderabbit** [comment]
@KaleabTessera Yeah, let's do it. I'm being stupid

**Comment by KaleabTessera** [comment]
@jaderabbit Cool, but I get what you are saying, all sensitive env variables we will store in circleci.

**Pull request merged**
