### PR TITLE
Review integration

### PR DESCRIPTION
**Pull request by avishkar58**

### CODE REVIEW

**Comment by avishkar58** [comment]
@greeffjean For your reference - please see the changes to services resulting from integration with the real backend, and also some refactoring I did to clean up some variable names and/or simplify the code.

**Comment by greeffjean** [comment]
> @greeffjean For your reference - please see the changes to services resulting from integration with the real backend, and also some refactoring I did to clean up some variable names and/or simplify the code.

HI, okay great, Im trying to understand why the delete and tag models where removed? Did you do that?

**Comment by avishkar58** [comment]
I did remove the delete modal because we already have a component for
confirming an action. The tag modal should still be there though?

**Comment by greeffjean** [comment]
Sorry, I thought I deleted this comment, I figured it out, code looks
better this way thanks, I'm stuck on iss799 , there is a corset policy on
review.service that's blocking me

**Pull request merged**
